:source-highlighter: highlight.js
:highlightjs-languages: PowerShell
:sectanchors: 
:url-repo: https://github.com/AdoptOpenJDK/website-adoptium-documentation

= Installation
We're currently working out our installation page. Please check back later!

Temurin binaries are available for https://adoptium.net/releases.html[download] in the following types of installation package:

* xref:#archives[Archive]
* xref:#installers[Installers]
* xref:#pkgmgr[Package Managers]

The binaries are supported on the architectures and operating systems listed in xref:../support/index.adoc[Supported Platforms]. If you're migrating to Temurin, you can learn about the differences between Oracle JDK and Temurin in our xref:../migration/index.adoc[Migration Guide] and any steps that you might need to take.

[#archives]
== Archives
The installation from archive has a general and platform specific part.
First follow the geneal steps to download the correct archive:

1. Go to https://adoptium.net/releases.html[Adoptiums Relaeses] page
2. Select your desired version from the list
3. Select your operating system and architecure
4. Download the `.zip` or `.tar.gz` file
5. Move the archive to a directory that will not move or be deleted

NOTE: Use the checksum to ensure the authenticity of your binary.
The Instructions are within the platform specific sections.

=== Linux, Alpine and macOS
Open a terminal and navigate to the directory containing the archive.

==== Checking the SHA-256 checksum
1. Run the following command to calcualte the checksum
[source,Bash]
sha256sum OpenJDK<version>-<platform>_<JVM>_<version>.tar.gz

2. Compare the result with the checksum from https://adoptium.net/releases.html[Adoptiums Relaeses] page

==== Install Adoptium
1. Extract the `.tar.gz.` You can use the following command:
[source,Bash]
tar xzf OpenJDK<version>-<platform>_<JVM>_<version>.tar.gz

2. Add this version of Java to your `PATH`:
[source,Bash]
export PATH=$PWD/jdk-<version>/bin:$PATH

3. Check that Java has installed correctly:
[source,Bash]
java -version

=== Windows
Open the Command Prompt and navigate to the directory containing the archive.

==== Checking the SHA-256 checksum
1. Run the following command to calcualte the checksum
[source,Powershell]
certutil -hashfile OpenJDK<version>-<platform>_<JVM>_<version>.zip SHA256

2. Compare the result with the checksum from https://adoptium.net/releases.html[Adoptiums Relaeses] page

==== Install Adoptium
1. Extract the `.zip` You can use the following command:
[source,Powershell]
Expand-Archive -Path .\OpenJDK<version>-<platform>_<JVM>_<version>.zip -DestinationPath .

2. Add this version of Java to your `PATH`:
[source,Powershell]
set PATH=%cd%\jdk-<version>\bin;%PATH%

3. Check that Java has installed correctly:
[source,Powershell]
java -version

[#installers]
== Installers
Installers are currently available for Windows® and macOS® JDK and JRE packages. Installation steps are covered in the following sections:

* xref:#win_msi[Windows MSI installer packages]
* xref:#macos_inst[macOS PKG installer packages]

[#win_msi]
=== Windows MSI installer packages
Temurin Windows installer packages are available as standard .msi files, which can be run with an interactive user interface or run silently from the command line. The installer is designed for use on a per-machine basis, not per-user basis, so you can have only one installation of the MSI on a machine for all users.

NOTE: Windows installer packages are supported only on Windows x64 systems.

==== GUI installation
Instructions for running an interactive installation using the Windows MSI installer.

1. https://adoptium.net/releases.html[Download] the .msi file.
Open it to launch the installation program.

2. Read and accept the license if you are happy with the terms.

3. On the Custom Setup screen you can choose the features that you want to install and optionally change the default installation directory.
By default, Temurin installs to `c:\Program Files\Temurin\<package>` with the following features, which you can deselect, if necessary:

** Add the installation to the PATH environment variable
** Associate .jar files with Java applications

+
Additional features can be selected by clicking on the directory tree where you see a check mark (x).
 These features include:
** Updating the `JAVA_HOME` environment variable

4. When you have chosen the features that you want to install, click Next.

5. Click Install to begin the installation.

6. When the installation is finished, click Finish to close the program.

==== Command-line installation
A silent installation allows you to install the Windows package with pre-selected features without user interaction, which can be useful for widescale deployment.
Follow these steps:

1. https://adoptium.net/releases.html[Download] the .msi file.

2. Choose the features that you want to install, which are shown in the following table:
|===
|Feature| Description

|`FeatureMain`| Core Temurin installation (DEFAULT)
|`FeatureEnvironment`| the PATH environment variable (DEFAULT)
|`FeatureJarFileRunWith`|Associate .jar files with Java applications (DEFAULT)
|`FeatureJavaHome`| Update the JAVA_HOME environment variable
|`FeatureOracleJavaSoft`| Updates registry keys HKLM\SOFTWARE\JavaSoft\
|===

NOTE: `FeatureOracleJavaSoft` can be used to prevent Oracle Java launching from `PATH` when Temurin is uninstalled. Reinstall Oracle Java if you need to restore the Oracle registry keys.

Optional parameters can be used that group some of the features together:

|===
|Parameter| Features

|INSTALLLEVEL=1| FeatureMain, FeatureEnvironment, FeatureJarFileRunWith 
|===

3. Run the command on the target workstation.

The following example silently installs Temurin, updates the `PATH`, associates `.jar` files with Java applications and defines `JAVA_HOME`:
[source,Powershell]
msiexec /i <package>.msi ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome INSTALLDIR="c:\Program Files\Eclipse Foundation\" /quiet

NOTE: You must use INSTALLDIR with FeatureMain.

The following example silently installs all the features for `INSTALLLEVEL=1`:
[source,Powershell]
msiexec /i <package>.msi INSTALLLEVEL=1 /quiet

If you want to launch an interactive installation in another language you can use the Windows installer `TRANSFORMS` option to set your language choice.
For example, to set the UI language to German, use code 1031, which must be preceded by a :.
[source,Powershell]
msiexec /i <package>.msi INSTALLLEVEL=1 TRANSFORMS=:1031

For a list of supported codes, see the Language list.

===== Reinstalling or upgrading
To reinstall Temurin in silent mode with default features, run the following command:
[source,Powershell]
msiexec /i <package>.msi REINSTALL=ALL /quiet

If you want to upgrade Temurin in silent mode, run the following command:
[source,Powershell]
msiexec /i <package>.msi REINSTALL=ALL REINSTALLMODE=amus /quiet

REINSTALLMODE options: (from Control Events)
[horizontal]
a:: Force all files to be installed regardless of checksum or version
m:: Rewrite all required registry entries from the Registry Table that go to the `HKEY_LOCAL_MACHINE`
o:: Reinstall if the file is missing or is an older version
u:: Rewrite all required registry entries from the Registry Table that go to the `HKEY_CURRENT_USER` or `HKEY_USERS`
s:: Reinstall all shortcuts and re-cache all icons overwriting any existing shortcuts or icons

NOTE: `REINSTALL=ALL` automatically sets `REINSTALLMODE=omus`

===== Upgrade limitation:

Upgrading .msi files works only for the first 3 digits of the build number due to an https://docs.microsoft.com/de-de/windows/win32/msi/productversion[MSI limitation]:

* Upgrading 8.0.2.1 to 8.0.3.1 works.
* Upgrading 8.0.2.1 to 8.0.2.2 does not work. Uninstall the previous .msi and install the new one.
* Upgrading 8.0.2.1 to 8.1.2.1 works.
* Upgrading 8.0.2.1 to 11.0.2.1 does not work. Temurin does not provide upgrades for major versions. Either keep both installations or uninstall the older one.

===== Reference reading
https://www.advancedinstaller.com/user-guide/msiexec.html[Msiexec.exe Command Line]

[#macos_inst]
=== macOS PKG installer packages
Temurin macOS installer packages are available as standard .pkg files, which can be run with an interactive user interface or run silently from the Terminal command line.

==== GUI installation
Instructions for running an interactive installation using the macOS PKG installer.

1. https://adoptium.net/releases.html[Download] the .pkg file.

2. Navigate to the folder that contains the file and open it to launch the installation program or drag the icon to your Application folder.

3. The Introduction screen indicates the target location for the installation, which you can change later in the install process.
Click Continue.

4. Read the license, click Continue and accept the license if you are happy with the terms.

5. Change the target location for the installation.
Click Install to complete the installation.

==== Command-line installation
A silent installation allows you to install the macOS package without user interaction, which can be useful for widescale deployment.
You must have administrator privileges.
Follow these steps:

1.  https://adoptium.net/releases.html[Download] the .pkg file.

2. Launch the Terminal app (terminal.app).

3. Run the following command:
[source,Bash]
installer -pkg <path_to_pkg>/<pkg_name>.pkg -target /

4. Enter the Administrator password.

5. Temurin installs to `/Library/Java/JavaVirtualMachines/temurin-<version>.<jdk|jre>/`

[#pkgmgr]
== Package Managers
Package managers are currently available for Windows.
Installation steps are covered in the following sections:

=== Windows winget
Temurin Windows installer packages are available on winget, which can be run silently from the command line. The installer is designed for use on a per-machine basis, not per-user basis, so you can have only one installation of the MSI on a machine for all users.

NOTE: Windows installer packages are supported only on Windows x64 systems.

==== Winget installation
Run the following command to install the package.
[source,Powershell]
winget install EclipseFoundation.AdoptiumOpenJDK.17

NOTE: You can install a different major version by change the version number at the end of the package name.

==== Winget upgrade
Run the following command to upgrade the package to the latest minor version of the currently installed major version.
[source,Powershell]
winget upgrade EclipseFoundation.AdoptiumOpenJDK.17

==== Winget uninstall
Run the following command to uninstall the package.
[source,Powershell]
winget uninstall EclipseFoundation.AdoptiumOpenJDK.17